/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function parse(input: string): string;

export declare function render(input: string): string;

export declare function renderFast(input: string): string;

export interface RenderOptions {
	sanitize?: boolean;
	syntaxHighlight?: boolean;
	toc?: boolean;
	directives?: boolean;
}

export declare function renderWithOptions(
	input: string,
	options?: RenderOptions | undefined | null,
): string;
